# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
# JDK 8 is set to deploy the docs and artifacts
  - openjdk8
env:
  - DEPLOY=true DEPLOY_DOCS=true LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH PATH=/usr/local/bin:$PATH

before_install:
  - sudo apt-get update
  # install JSpell
  - sudo apt-get -y install build-essential gcc-multilib perl cpanminus
  - cpanm --sudo Lingua::Jspell::EAGLES
  - sudo jspell-installdic src/main/resources/jspell/*
  # Gets scripts
  - git clone -b v1.2.2 --single-branch https://github.com/josepaiva94/ci-shell-scripts.git ~/.scripts
  # Sets scripts as executable
  - chmod -R +x ~/.scripts/*
  # Prepares CI environment
  - source ~/.scripts/travis/load-travis-environment.sh
before_script:
  # Creates Maven settings
  - ~/.scripts/java/maven/create-maven-settings.sh $VERSION_TYPE
script:
  # Unit and integration tests are run
  - mvn clean verify -Denv.UJSPELL_PATH=$(which ujspell)
after_success:
  # Documentation deployment script
  - ~/.scripts/java/maven/deploy-site.sh $DO_DEPLOY_DOCS deployment
  # Code artifacts deployment script
  - ~/.scripts/java/maven/deploy.sh $DO_DEPLOY deployment
